### ISSUE TITLE
"DATA IN ENCRYPTED SQL FILES"

### ISSUE THREAD

**Issue by callmeulas** [t3l3machus/eviltree#1]
Can this script retrieve information from local "cookie" files based on SQL of internet browsers?
EXAMPLE
![image](https://user-images.githubusercontent.com/96961115/227499553-3e0204c2-0823-43df-b8fd-4bd52a8b31f5.png)

**Comment by t3l3machus** [comment]
Hi @yoap, yes it can, you will have to use the `-b` argument. Here's an example with firefox's `cookies.sqlite` file (I moved it in a test dir because eviltree would scan everything in the original one and the output would be intense). **Note** that, in action, you might not see results from these files because they are used by some system process and eviltree fails to open them for reading etc:    

![image](https://user-images.githubusercontent.com/75489922/227782048-fe1c453b-df03-40c9-8e96-496fe72a7fca.png)
